import { Source_Code_Pro } from "next/font/google";
import "./globals.css";

const source_code_pro = Source_Code_Pro({ subsets: ["latin"], weight:["400", "500", "600", "700"] });

export const metadata = {
  title: "Blogger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={source_code_pro.className}>{children}</body>
    </html>
  );
}
